<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>
    <form>
        <input type="text" name="search" id="search" placeholder="Search">
        <button type="submit">Go</button>
    </form>
    <ul>
    <?php if (empty($users)) : ?>
        <li><b>Not found</b></li>
    <?php endif; ?>
    <?php foreach ($users as $user) : ?>
        <li><?= $user ?></li>
    <?php endforeach; ?>
    </ul>
</body>
</html>